services:
  db:
    image: ankane/pgvector
    container_name: ai_postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ai_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5

  web:
    build:
      context: .
    container_name: ai_backend
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./data:/app/data
    command: uvicorn app.main:app --host 0.0.0.0 --port ${PORT} --workers 4
    networks:
      - ai_net

volumes:
  postgres_data:

networks:
  ai_net: